service: kdg-solution-3

frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm
    excludeFiles: src/**/*.test.js

functions:
  IngestionWorker:
    environment:
      ORDER_RECIEVED_TOPIC: !Ref OrderRecievedTopic
      RESTAURANT_NOTIFIED_TOPIC: !Ref RestaurantNotifiedTopic
      ORDER_ACCEPTED_TOPIC: !Ref OrderAcceptedTopic
      USER_NOTIFIED_TOPIC: !Ref UserNotifiedTopic
      ORDER_COMPLETED_TOPIC: !Ref OrderCompletedTopic
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - IngestionStream
              - Arn
          batchSize: 100
          parallelizationFactor: 1
    handler: src/ingestion-worker.default
    iamRoleStatements:
      - Effect: Allow     
        Action:
          - sns:*        
        Resource: !Ref OrderRecievedTopic
      - Effect: Allow     
        Action:
          - sns:*        
        Resource: !Ref RestaurantNotifiedTopic
      - Effect: Allow     
        Action:
          - sns:*        
        Resource: !Ref OrderAcceptedTopic
      - Effect: Allow     
        Action:
          - sns:*        
        Resource: !Ref UserNotifiedTopic
      - Effect: Allow     
        Action:
          - sns:*        
        Resource: !Ref OrderCompletedTopic
  
  OrderRecieved:
    handler: src/order-recieved.default
    events:
      - sns:
          arn: !Ref OrderRecievedTopic
          topicName: OrderRecievedTopic

  RestaurantNotified:
    handler: src/restaurant-notified.default
    events:
      - sns:
          arn: !Ref RestaurantNotifiedTopic
          topicName: RestaurantNotifiedTopic
  
  OrderAccepted:
    handler: src/order-accepted.default
    events:
      - sns:
          arn: !Ref OrderAcceptedTopic
          topicName: OrderAcceptedTopic

  UserNotified:
    handler: src/user-notified.default
    events:
      - sns:
          arn: !Ref UserNotifiedTopic
          topicName: UserNotifiedTopic

  OrderCompleted:
    handler: src/order-completed.default
    events:
      - sns:
          arn: !Ref OrderCompletedTopic
          topicName: OrderCompletedTopic

resources:
  Resources:
    IngestionStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: kdg-solution-3-stream
        ShardCount: 1
    
    OrderRecievedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: OrderRecievedTopic
    RestaurantNotifiedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: RestaurantNotifiedTopic
    OrderAcceptedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: OrderAcceptedTopic
    UserNotifiedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: UserNotifiedTopic
    OrderCompletedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: OrderCompletedTopic
